package com.gamemasterx.server.security;

import com.gamemasterx.server.filter.CsrfFilter;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpSession;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Map;

@RestController
@RequestMapping("/api/csrf")
public class CsrfTokenController {

    @GetMapping("/token")
    public Map<String, String> getToken(HttpServletRequest request) {
        HttpSession session = request.getSession(true);
        String token = (String) session.getAttribute(CsrfFilter.CSRF_SESSION_ATTR);
        if (token == null) {
            // Token will be generated by filter on next request; ensure existence
            token = "";
        }
        return Map.of("csrfToken", token);
    }
}
